apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-deploy
spec:
  replicas: REPLICAS
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata: 
      name: java-demo
      labels:
        app: java-demo
    spec:
      nodeSelector:
        jenkins: "true"
      imagePullSecrets:
      - name: SECRET_NAME
      containers:
      - name: java-demo
        image: IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-demo-svc
spec:
  selector:
    app: java-demo
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30088
